### ISSUE TITLE
Using the modified libviso2

### ISSUE THREAD

**Issue by mhkabir** [dphoyes/OpenCL-Structure-from-Motion#1]
Really nice job you've done here. I want to get the viso2 library running with OpenCL for FPGAs and GPUs.

I will be using the stereo_odometer, do you have any suggestions?

Would this work as drop-in for viso2? Anything I should keep in mind?

**Comment by dphoyes** [comment]
Hi there. As far as I know this should work as a drop-in replacement for libviso2. The master branch contains the x86+GPU targeted version, and the socfpga branch contains the ARM+FPGA one. However, I believe the sections which are ported to OpenCL all belong to the monocular implementation, which don't really provide any benefit for the stereo mode. You'd therefore probably have to invest a fair amount of effort in developing a similar OpenCL implementation for viso_stereo.
